### ISSUE TITLE
greedy k-center algorithm

### ISSUE THREAD

**Issue by nutellamok** [stanford-futuredata/selection-via-proxy#2]
Dear authors,

I have a question regarding the implementation of the greedy k-center algorithm.

When I run the greedy k-center algorithm with your code, I always get 1000 (which corresponds to the size of the initial subset) more points than the number I specified through the "subset" argument.

Could you explain why this might be happening?

Thank you.

**Comment by codyaustun** [comment]
@nutellamok I see you closed this issue. Does that mean you figured out the answer by yourself or are you still waiting for a response?

**Comment by nutellamok** [comment]
I figured it out by myself -- I apologize for any inconvenience I may have caused.

**Comment by MichaelDoron** [comment]
I think I ran into the same question as @nutellamok, but I haven't figured it out by myself: 

From what I understood, the k center greedy algorithm should return an array `s` in the size of the budget `b` after removing the previous selection `s0`, as in the pseudocode `return s \ s0`. However, at the end of the function `select`, the returned core-set is `updated = np.concatenate([current, new])`, which adds the randomly selected `current` (which is `s0`) to `s`.

Could you please help me understand what I'm missing?

**Comment by codyaustun** [comment]
Thanks, @MichaelDoron! I think I understand the issue. You're running the `coreset` code, and the returned subset is of size `b + 1000` rather than `b`, right? If so, it looks like I forgot to decrease the budget after creating `s0` (`b' = b - |s0|`) when I reimplemented the original code. I'll fix this. In the meantime, you can work around it by setting subset to the be value you want -1000 for k-centers.

**Comment by MichaelDoron** [comment]
Thanks @codyaustun! That's what I did in the meanwhile. I appreciate your answer!
